using System.ComponentModel.DataAnnotations;

namespace Lealthy_Hospital_Application_System.Enum;

public enum LaboratoryTests
{
    [Display(Name ="Abdominal Mass FNA")]
    AbdominalFNA = 1,
    [Display(Name ="Acid Base Status")]
    AcidBaseStatus = 2,
    [Display(Name ="ACR")]
    ACR = 3,
    [Display(Name ="Actual Bicarbonate")]
    ActualBicarbonate = 4,
    [Display(Name ="Acute Kidney Injure Score")]
    AcuteKidney = 5,
    [Display(Name ="Adenovirus")]
    Adenovirus = 6,
    [Display(Name ="Anti HBs")]
    AntiHBs = 7,
    [Display(Name ="Antibiotic Tests")]
     Antibiotic = 9,
    [Display(Name ="Anti-HCV")]
    AntiHCV = 10,
    [Display(Name ="Anti-Hepatitis BS")]
    AntiHepatitis = 11,
    [Display(Name ="Anti-HIV")]
    AntiHIV = 12,
    [Display(Name ="Beta 2 Glycoprotein")]
    BetaGlycoprotein = 13,
    [Display(Name ="Bicarbonate")]
    Bicarbonate = 14,
    [Display(Name ="BK Virus")]
    BKVirus = 15,
    [Display(Name ="Blood Group")]
    BloodGroup = 16,
    [Display(Name ="Blood Transfusion")]
    BloodTransfusion = 17,
    [Display(Name ="Breath Hydrogen Test")]
    BreathHydrogen = 18,
    [Display(Name ="C1 Esterase Inhibitor")]
    EsteraseInhibitor = 19,
    [Display(Name ="Calcium (Blood and Urine)")]
    CalciumBlood = 20,
    [Display(Name ="Calcium (Plasma Total)")]
    CalciumPlasma = 21,
    [Display(Name ="Candida PCR")]
    CandidaPCR = 22,
    [Display(Name ="Cardiac Muscle Antibodies")]
    Cardiac = 23,
    [Display(Name ="DNA Testing")]
    DNATesting = 24,
    [Display(Name ="Drugs of Abuse")]
    Drugs = 25,
    [Display(Name ="Electrolytes")]
    Electrolytes = 26,
    [Display(Name ="Factor II Assay")]
    FactorII = 27,
    [Display(Name ="Factor IX Assay")]
    FactorIX = 28,
    [Display(Name ="Free Fatty Acids")]
    FreeFattyAcids = 29,
    [Display(Name ="Gases")]
    Gases = 30,
    [Display(Name ="Glucose")]
    Glucose = 31,
    [Display(Name ="Growth Hormone")]
    GrowthHormone = 32,
    [Display(Name ="HBV confirmation")]
    HBVConfirmation = 33,
    [Display(Name ="Hepatitis A Virus")]
    HepatitisA = 34,
    [Display(Name ="Hepatitis B Virus")]
    HepatitisB = 35,
    [Display(Name ="Immunocytochemistry")]
    Immunocytochemistry = 36,
    [Display(Name ="Immunoglobulins")]
    Immunoglobulins = 37,
    [Display(Name ="Inflammatory/non-inflammatory Bursitis")]
    Inflammatory = 38,
    [Display(Name ="Insulin")]
    Insulin = 39,
    [Display(Name ="Iron")]
    Iron = 40,
    [Display(Name ="Lactate")]
    Lactate = 41,
    [Display(Name ="Liver Function")]
    LiverFunction = 42,
    [Display(Name ="Magnesium (Blood and Urine)")]
    Magnesium = 43,
    [Display(Name ="Oral Anticoagulant Control (INR)")]
    Oral = 44,
    [Display(Name ="Osmolality (Blood and Urine)")]
    Osmolatity = 45,
    [Display(Name ="Paracetamol")]
    Paracetamol = 46,
    [Display(Name ="Q Fever Serology and PCR")]
    QFever = 47,
    [Display(Name ="Renal FNA")]
    RenalFNA = 48,
    [Display(Name ="Testosterone")]
    Testosterone = 49,
    [Display(Name ="Triglycerides")]
    Triglycerides = 50,
    [Display(Name ="Urethral washing")]
    UrethralWashing = 51,
    
}