using System.ComponentModel.DataAnnotations;

namespace Lealthy_Hospital_Application_System.Enum;

public enum IllnessesList
{
    [Display(Name ="Acne")]
    Acne = 1,
    [Display(Name ="Abdominal Pain")]
    AbdominalPain = 2,
    [Display(Name ="Allergies")]
    Allergies = 3,
    [Display(Name ="Anxiety")]
    Anxiety = 4,
    [Display(Name ="Appendicitis")]
    Appendicitis = 5,
    [Display(Name ="Asthma")]
    Asthma = 6,
    [Display(Name ="Bacterial")]
    Bacterial = 7,
    [Display(Name ="Bipolar Disorder")]
    BipolarDisorder = 8,
    [Display(Name ="Cardiovascular disease")]
    Cardiovascular = 9,
    [Display(Name ="Chest Pain")]
    ChestPain = 10,
    [Display(Name ="Chickenpox")]
    Chickenpox = 11,
    [Display(Name ="Cough")]
    Cough = 12,
    [Display(Name ="Coronavirus")]
    CoronaVirus = 13,
    [Display(Name ="Depression")]
    Depression = 14,
    [Display(Name ="Diabetes")]
    Diabetes = 15,
    [Display(Name ="Diarrhoea")]
    Diarrhoea = 16,
    [Display(Name ="Epilepsy")]
    Epilepsy = 17,
    [Display(Name ="Erectile Dysfunction")]
    ErectileDysfunction = 18,
    [Display(Name ="Farting")]
    Farting = 19,
    [Display(Name ="Fever in Adults")]
    FeverAdult = 20,
    [Display(Name ="Fever in Children")]
    FeverChildren = 21,
    [Display(Name ="Flu")]
    Flu = 22,
    [Display(Name ="Food Allergy")]
    FoodAllergy = 23,
    [Display(Name ="Gastroenteritis")]
    Gastroenteritis = 24,
    [Display(Name ="Genital warts")]
    GenitalWarts = 25,
    [Display(Name ="Headaches")]
    Headaches = 26,
    [Display(Name ="HIV")]
    HIV = 27,
    [Display(Name ="Insomnia")]
    Insomnia = 28,
    [Display(Name ="Indigestion")]
    Indigestion = 29,
    [Display(Name ="Kidney Stones")]
    KidneyStones = 30,
    [Display(Name ="Labyrinthitis")]
    Labyrinthitis = 31,
    [Display(Name ="Leg Cramps")]
    LegCramps = 32,
    [Display(Name ="Liver Disease")]
    LiverDisease = 33,
    [Display(Name ="Lupus")]
    Lupus = 34,
    [Display(Name ="Malaria")]
    Malaria = 35,
    [Display(Name ="Menopause")]
    Menopause = 36,
    [Display(Name ="Migraine")]
    Migraine = 37,
    [Display(Name ="Miscarriage")]
    Miscarriage = 38,
    [Display(Name ="Neck Problems")]
    NeckProblems = 39,
    [Display(Name ="Obesity")]
    Obesity = 40,
    [Display(Name ="Osteosarcoma")]
    Osteosarcoma = 41,
    [Display(Name ="Pneumonia")]
    Pneumonia = 42,
    [Display(Name ="Pulmonary Hypertension")]
    Pulmonary = 43,
    [Display(Name ="Rare Conditions")]
    RareConditions = 44,
    [Display(Name ="Sleep Apnea")]
    SleepApnea = 45,
    [Display(Name ="Sinusitis")]
    Sinusitis = 46,
    [Display(Name ="Sore Throat")]
    SoreThroat = 47,
    [Display(Name ="Urinary Incontinence")]
    Urinary = 48,
    [Display(Name ="Vomiting")]
    Vomiting = 49,
    [Display(Name ="Zika Virus")]
    ZikaVirus = 50,
}